---
  name: 🆘 Help wanted MultipleWiki
  
  on:
    issues:
      types: [opened]
  
  jobs:
    issue:
      name: 🔍 Get inputs
      if: ${{ contains(github.event.issue.labels.*.name, 'help wanted') }}
      runs-on: ubuntu-latest
      outputs:
        helpneededwith: ${{ steps.inputs.outputs.help_needed_with }}
        wiki: ${{ steps.inputs.outputs.documentation_page }}
      steps:
        - name: 📥 Get inputs
          id: inputs
          uses: drdonoso/issueform-get-inputs@main
          with:
            body: ${{ github.event.issue.body }}
      
    execute:
      needs: issue
      uses: IAExperiments/WikiChatbot/.github/workflows/reusable-workflow.yml@main
      secrets: 
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      with:
        query: ${{ needs.issue.outputs.helpneededwith }}
        AZURE_OPENAI_API_ENDPOINT: ${{ vars.AZURE_OPENAI_API_ENDPOINT }}
        AZURE_OPENAI_API_INSTANCE_NAME: ${{ vars.AZURE_OPENAI_API_INSTANCE_NAME }}
        AZURE_OPENAI_API_VERSION: ${{ vars.AZURE_OPENAI_API_VERSION }}
        AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME }}
        BASEIMAGEURL: ${{ vars.BASEIMAGEURL }}